version: '3.8'

services:
  auth-db:
    container_name: "user-auth-db"
    image: "mysql:8.0.32"
    restart: always
    ports:
      - "3312:3306"
    expose:
      - "3312"
    volumes:
      - db_auth:/data
    environment:
      MYSQL_DATABASE: login_db
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass1
      MYSQL_ROOT_PASSWORD: root

  user-events-mongodb:
    image: mongo:7.0.8
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - user-events-mongo-data:/data/db

volumes:
  db_auth:
  user-events-mongo-data: