version: '3.8'

services:

  auth-db:
    container_name: "user-auth-db"
    image: "mysql:8.0.32"
    restart: always
    ports:
      - "3312:3306"
    expose:
      - "3312"
    volumes:
      - db_auth:/data
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass1
      MYSQL_ROOT_PASSWORD: root

  notification-config-db:
    container_name: "notification-config-db"
    image: "mysql:8.0.32"
    restart: always
    ports:
      - "3314:3306"
    expose:
      - "3314"
    volumes:
      - notification-config-db:/data
    environment:
      MYSQL_DATABASE: notification-config-db
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass1
      MYSQL_ROOT_PASSWORD: root

  user-events-mongodb:
    image: mongo:7.0.8
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - user-events-mongo-data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  db_auth:
  notification-config-db:
  user-events-mongo-data: