#!/bin/bash

./mvnw clean package spring-boot:repackage

APP_VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml)

if [ -z "$APP_VERSION" ]; then
  echo "Error: Could not extract version from pom.xml"
  exit 1
fi

docker build --build-arg APP_VERSION="${APP_VERSION}" -t ms-config:"${APP_VERSION}" .