server:
  port: 8888

#spring:
#  application:
#    name: ms-config
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/configs

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EderV/spring-ms-app-config
          search-paths: '{application}'